{"headline": "iPad", "links": "https://www.wsj.comhttp://topics.wsj.com/subject/A/apple-ipad/5857"}
{"headline": "Apple Faces Two Federal Probes Over iPhone Battery Issue", "links": "https://www.wsj.com/articles/apple-facestwo-federal-probesover-iphone-battery-issue-1517348203?mod=searchresults&page=1&pos=1"}
{"headline": "Samsung Cashes In on Chips to Hit Another Record Profit", "links": "https://www.wsj.com/articles/samsung-cashes-in-on-chips-to-hit-another-record-profit-1517360430?mod=searchresults&page=1&pos=2"}
{"headline": "AT&T Earnings: What to Watch", "links": "https://www.wsj.com/articles/at-t-earnings-what-to-watch-1517344550?mod=searchresults&page=1&pos=3"}
{"headline": "Brooklyn Couple Offers Artists a Country Refuge\u2014For Free", "links": "https://www.wsj.com/articles/brooklyn-couple-offers-artists-a-country-refugefor-free-1517335088?mod=searchresults&page=1&pos=4"}
{"headline": "iPhone Supply Shock Won\u2019t Upend Europe\u2019s Star Chip Maker", "links": "https://www.wsj.com/articles/iphone-supply-shock-wont-upend-europes-star-chip-maker-1517334983?mod=searchresults&page=1&pos=5"}
{"headline": "Apple to Cut iPhone X Production in the Face of Weak Demand", "links": "https://www.wsj.com/articles/apple-to-curtail-iphone-x-production-in-the-face-of-weak-demand-1517312098?mod=searchresults&page=1&pos=6"}
{"headline": "WSJ City PM: Market Rally Takes a Pause, Eurozone Growth Outstrips US, Three US Mega-Caps Tackle Healthcare", "links": "https://www.wsj.comhttps://www.wsj.com/articles/wsj-city-pm-market-rally-takes-a-pause-eurozone-growth-outstrips-us-three-us-mega-caps-tackle-healthcare-1517334745?mod=searchresults&page=1&pos=7"}
{"headline": "Carlos Slim, One of World\u2019s Richest Men, Gets Schooled by an Old Pupil", "links": "https://www.wsj.com/articles/carlos-slim-one-of-worlds-richest-men-gets-schooled-by-an-old-pupil-1517331422?mod=searchresults&page=1&pos=8"}
{"headline": "Stocks to Watch: Apple, MetLife, Amazon, Aetna, Wal-Mart, McDonald\u2019s, Maxim, Callidus, Reuters, Pfizer", "links": "https://www.wsj.comhttps://www.wsj.com/articles/stocks-to-watch-apple-metlife-amazon-aetna-wal-mart-mcdonalds-maxim-callidus-reuters-pfizer-1517322758?mod=searchresults&page=1&pos=9"}
{"headline": "New York Pension Fund Doubles Bet on Low-Carbon Companies", "links": "https://www.wsj.com/articles/new-york-pension-fund-doubles-bet-on-low-carbon-companies-1517320801?mod=searchresults&page=1&pos=10"}
{"headline": "The Morning Download: SAP CEO Says Callidus Acquisition Accelerates Move to Cloud", "links": "https://www.wsj.comhttps://www.wsj.com/articles/the-morning-download-sap-ceo-says-callidus-acquisition-accelerates-move-to-cloud-1517320036?mod=searchresults&page=1&pos=11"}
{"headline": "The Morning Risk Report: SEC in Texas Flags \u2018Canned\u2019 Compliance Programs", "links": "https://www.wsj.comhttps://www.wsj.com/articles/the-morning-risk-report-sec-in-texas-flags-canned-compliance-programs-1517318153?mod=searchresults&page=1&pos=12"}
{"headline": "CMO Today: Madison Ave Prepares for Super Bowl; NBC\u2019s Lack Wants Facebook to Pay; Media Agency Reviews Pick Up Pace", "links": "https://www.wsj.com/articles/cmo-today-madison-ave-prepares-for-super-bowl-nbcs-lack-wants-facebook-to-pay-media-agency-reviews-pick-up-pace-1517317594?mod=searchresults&page=1&pos=13"}
{"headline": "The 10-Point.", "links": "https://www.wsj.com/articles/the-10-point-1517313692?mod=searchresults&page=1&pos=14"}
{"headline": "Today\u2019s Top Supply Chain and Logistics News From WSJ", "links": "https://www.wsj.com/articles/todays-top-supply-chain-and-logistics-news-from-wsj-1517313681?mod=searchresults&page=1&pos=15"}
{"headline": "How the Tax Overhaul Will Affect Tech Companies\u2019 Earnings", "links": "https://www.wsj.com/articles/how-the-tax-overhaul-will-affect-tech-companies-earnings-1517308201?mod=searchresults&page=1&pos=16"}
{"headline": "Sale of Slotomania Maker Playtika Hits Regulatory Snag in China", "links": "https://www.wsj.com/articles/sale-of-slotomania-maker-playtika-hits-regulatory-snag-in-china-1517308208?mod=searchresults&page=1&pos=17"}
{"headline": "The Daily Shot: The Global Bond Rout Is Spooking Stock Investors", "links": "https://www.wsj.comhttps://www.wsj.com/articles/the-daily-shot-the-global-bond-rout-is-spooking-stock-investors-1517285639?mod=searchresults&page=1&pos=18"}
{"headline": "Stocks to Watch: Apple, Dr. Pepper, Lockheed Martin, Avon, Intel, Lowe\u2019s, Wynn, Starbucks, AMD", "links": "https://www.wsj.comhttps://www.wsj.com/articles/stocks-to-watch-apple-dr-pepper-lockheed-martin-avon-intel-lowes-wynn-starbucks-amd-1517236389?mod=searchresults&page=1&pos=19"}
{"headline": "CMO Today: Celebrities Buy Fake Followers; Amazon\u2019s Advertising Progress; Facebook Earnings Preview", "links": "https://www.wsj.com/articles/cmo-today-celebrities-buy-fake-followers-amazons-advertising-progress-facebook-earnings-preview-1517231318?mod=searchresults&page=1&pos=20"}
